drop table if exists brands CASCADE 
drop table if exists customers CASCADE 
drop table if exists flavours CASCADE 
drop table if exists order_info CASCADE 
drop table if exists orders CASCADE 
create table brands (id integer generated by default as identity, price double not null, brand_name varchar(255), puff_count integer not null, primary key (id))
create table customers (id bigint generated by default as identity, address varchar(255), name varchar(255), phone_number varchar(255), primary key (id))
create table flavours (id bigint generated by default as identity, quantity integer not null, brand_name varchar(255), flavour_name varchar(255), primary key (id))
create table order_info (id bigint generated by default as identity, customerid bigint, orderid bigint, date_placed date, delivery_date date, primary key(id))
create table orders (id bigint generated by default as identity, brandid integer not null, brand_name varchar(255), flavourid bigint, flavour_name varchar(255), item_quantity integer not null, order_price double not null, primary key (id))